# coding: utf-8

# flake8: noqa
"""
    SDS Client Service API

     This API can be used for: - get collectors configuration by query or by ID - get datasets by a search query or by ID - get files by path, search query over datasets, by ID, or by a subset/combination of results from a dataset query - get data as json by path, search query over datasets, by ID, or by a subset/combination of results from a dataset query 

    The version of the OpenAPI document: 0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from sds_client.models.collector import Collector
from sds_client.models.collector_id_list import CollectorIdList
from sds_client.models.datase_definition import DataseDefinition
from sds_client.models.dataset import Dataset
from sds_client.models.http_validation_error import HTTPValidationError
from sds_client.models.multi_response_collector import MultiResponseCollector
from sds_client.models.multi_response_dataset import MultiResponseDataset
from sds_client.models.sort_order import SortOrder
from sds_client.models.validation_error import ValidationError
from sds_client.models.validation_error_loc_inner import ValidationErrorLocInner
