# coding: utf-8

"""
    SDS Client Service API

     This API can be used for: - get collectors configuration by query or by ID - get datasets by a search query or by ID - get files by path, search query over datasets, by ID, or by a subset/combination of results from a dataset query - get data as json by path, search query over datasets, by ID, or by a subset/combination of results from a dataset query 

    The version of the OpenAPI document: 0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import List, Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr, conlist

class Collector(BaseModel):
    """
    Collector
    """
    name: StrictStr = Field(...)
    event_code: StrictInt = Field(...)
    pvs: conlist(StrictStr, unique_items=True) = Field(...)
    parent_path: Optional[StrictStr] = '/'
    collector_id: Optional[StrictStr] = None
    version: Optional[StrictInt] = 1
    created: datetime = Field(...)
    __properties = ["name", "event_code", "pvs", "parent_path", "collector_id", "version", "created"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Collector:
        """Create an instance of Collector from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> Collector:
        """Create an instance of Collector from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return Collector.parse_obj(obj)

        _obj = Collector.parse_obj({
            "name": obj.get("name"),
            "event_code": obj.get("event_code"),
            "pvs": obj.get("pvs"),
            "parent_path": obj.get("parent_path") if obj.get("parent_path") is not None else '/',
            "collector_id": obj.get("collector_id"),
            "version": obj.get("version") if obj.get("version") is not None else 1,
            "created": obj.get("created")
        })
        return _obj


