# coding: utf-8

"""
    SDS Client Service API

     This API can be used for: - get collectors configuration by query or by ID - get datasets by a search query or by ID - get files by path, search query over datasets, by ID, or by a subset/combination of results from a dataset query - get data as json by path, search query over datasets, by ID, or by a subset/combination of results from a dataset query 

    The version of the OpenAPI document: 0.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class SortOrder(str, Enum):
    """
    An enumeration.
    """

    """
    allowed enum values
    """
    DESC = 'desc'
    ASC = 'asc'

    @classmethod
    def from_json(cls, json_str: str) -> SortOrder:
        """Create an instance of SortOrder from a JSON string"""
        return SortOrder(json.loads(json_str))


