# coding: utf-8

"""
    SDS Client Service API

     This API can be used for: - get collectors configuration by query or by ID - get datasets by a search query or by ID - get files by path, search query over datasets, by ID, or by a subset/combination of results from a dataset query - get data as json by path, search query over datasets, by ID, or by a subset/combination of results from a dataset query 

    The version of the OpenAPI document: 0.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sds_client.api.collectors_api import CollectorsApi  # noqa: E501


class TestCollectorsApi(unittest.TestCase):
    """CollectorsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CollectorsApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_get_collector_collectors_id_get(self) -> None:
        """Test case for get_collector_collectors_id_get

        Get Collector  # noqa: E501
        """
        pass

    def test_query_collectors_collectors_get(self) -> None:
        """Test case for query_collectors_collectors_get

        Query Collectors  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
