# coding: utf-8

"""
    SDS Client Service API

     This API can be used for: - get collectors configuration by query or by ID - get datasets by a search query or by ID - get files by path, search query over datasets, by ID, or by a subset/combination of results from a dataset query - get data as json by path, search query over datasets, by ID, or by a subset/combination of results from a dataset query 

    The version of the OpenAPI document: 0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sds_client.api.json_api import JsonApi  # noqa: E501


class TestJsonApi(unittest.TestCase):
    """JsonApi unit test stubs"""

    def setUp(self) -> None:
        self.api = JsonApi()

    def tearDown(self) -> None:
        self.api.api_client.close()

    def test_get_json_by_dataset_id_json_dataset_id_get(self) -> None:
        """Test case for get_json_by_dataset_id_json_dataset_id_get

        Get Json By Dataset Id  # noqa: E501
        """
        pass

    def test_get_json_by_dataset_query_json_query_post(self) -> None:
        """Test case for get_json_by_dataset_query_json_query_post

        Get Json By Dataset Query  # noqa: E501
        """
        pass

    def test_get_json_by_path_json_get(self) -> None:
        """Test case for get_json_by_path_json_get

        Get Json By Path  # noqa: E501
        """
        pass

    def test_get_json_with_multiple_datasets_json_datasets_post(self) -> None:
        """Test case for get_json_with_multiple_datasets_json_datasets_post

        Get Json With Multiple Datasets  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
