# coding: utf-8

"""
    SDS Client Service API

     This API can be used for: - get collectors configuration by query or by ID - get datasets by a search query or by ID - get files by path, search query over datasets, by ID, or by a subset/combination of results from a dataset query - get data as json by path, search query over datasets, by ID, or by a subset/combination of results from a dataset query 

    The version of the OpenAPI document: 0.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from sds_client.models.sort_order import SortOrder  # noqa: E501

class TestSortOrder(unittest.TestCase):
    """SortOrder unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSortOrder(self):
        """Test SortOrder"""
        # inst = SortOrder()

if __name__ == '__main__':
    unittest.main()
